# Generated by Django 5.1 on 2026-06-11 04:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='メーカー名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommended', models.BooleanField(default=False, max_length=1, verbose_name='オススメ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, max_length=1, verbose_name='キャンセル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='注文詳細ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='注文数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.purchase')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
    ]
