# Generated by Django 5.1 on 2026-06-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
